# Generated by Django 2.0.3 on 2018-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='pictures/')),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
    ]
